// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserWebAPI.Data.Contexts;

#nullable disable

namespace UserWebAPI.Data.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20230422211736_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("UserWebAPI.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Admin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Admin");

                    b.Property<DateTime?>("BirthDay")
                        .HasColumnType("TEXT")
                        .HasColumnName("BirthDay");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedOn");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Gender");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Login");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("ModifiedOn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("Password");

                    b.Property<string>("RevokedBy")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("RevokedBy");

                    b.Property<DateTime?>("RevokedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("RevokedOn");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("28eb2822-b5cc-40c4-bc18-7b88b6cd3a8f"),
                            Admin = true,
                            BirthDay = new DateTime(2023, 4, 23, 0, 17, 36, 320, DateTimeKind.Local).AddTicks(8340),
                            CreatedBy = "GOD",
                            CreatedOn = new DateTime(2023, 4, 23, 0, 17, 36, 320, DateTimeKind.Local).AddTicks(8351),
                            Gender = 2,
                            Login = "admin",
                            Name = "Админ",
                            Password = "admin01"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
