// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UserWebAPI.Data.Contexts;

#nullable disable

namespace UserWebAPI.Data.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("UserWebAPI.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Admin")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Admin");

                    b.Property<DateTime?>("BirthDay")
                        .HasColumnType("TEXT")
                        .HasColumnName("BirthDay");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("CreatedOn");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Gender");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Login");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("ModifiedBy");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("ModifiedOn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("Password");

                    b.Property<string>("RevokedBy")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("RevokedBy");

                    b.Property<DateTime?>("RevokedOn")
                        .HasColumnType("TEXT")
                        .HasColumnName("RevokedOn");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ad86aa94-5417-4438-b34a-d37bfaf032e7"),
                            Admin = true,
                            BirthDay = new DateTime(2023, 4, 23, 3, 8, 40, 457, DateTimeKind.Local).AddTicks(3465),
                            CreatedBy = "GOD",
                            CreatedOn = new DateTime(2023, 4, 23, 3, 8, 40, 457, DateTimeKind.Local).AddTicks(3477),
                            Gender = 2,
                            Login = "admin",
                            Name = "Админ",
                            Password = "admin01"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
